update: flash-execute
change absolute directory for .img folder to current directory for more flexibility

Signed-off-by: Adinata <adinata.ch@proton.me>

diff --git a/src/flash-execute b/src/flash-execute
--- a/src/flash-execute
+++ b/src/flash-execute
@@ -7,7 +7,7 @@ b1="\033[34m"
 r5="\033[0m"
 
 LOG_FILE="flash.log"
-IMGS_DIR="images"
+IMGS_DIR="$(pwd)"
 
 log() {
     echo -e "${y1}$(date '+%Y-%m-%d %H:%M:%S')${r5} - $1" | tee -a "$LOG_FILE"
@@ -22,77 +22,118 @@ confirm() {
     esac
 }
 
+check_images() {
+    local img_count=$(ls *.img *.bin 2>/dev/null | wc -l)
+    if [ "$img_count" -eq 0 ]; then
+        log "${r3}ERROR: No .img or .bin files found in current directory!${r5}"
+        log "Please cd to the directory containing your firmware images"
+        exit 1
+    fi
+}
+
+erase_partitions() {
+    log "${r3}Starting data wipe...${r5}"
+    
+    partitions=("userdata" "cache" "metadata" "cust")
+    
+    for partition in "${partitions[@]}"; do
+        if confirm " Erase ${partition} partition?"; then
+            log "${b1}Erasing ${partition}...${r5}"
+            fastboot erase "$partition" || {
+                log "${r3}Failed to erase ${partition}!${r5}"
+            }
+        fi
+    done
+    
+    log "${g3}Data wipe completed!${r5}"
+}
+
 dv_vbmeta() {
     local vbmeta_file="$1"
     local partition=$(basename "$vbmeta_file" .img)
     
     if confirm " ${y1}'Disable verity/verification'${r5} for ${partition}"; then
-        log "${b1} Flashing ${partition} with verity disabled...${r5}"
+        log "${b1}Flashing ${partition} with verity disabled...${r5}"
         fastboot --disable-verity --disable-verification flash "$partition" "$vbmeta_file"
     else
-        log "${b1} Flashing ${partition} normally...${r5}"
+        log "${b1}Flashing ${partition} normally...${r5}"
         fastboot flash "$partition" "$vbmeta_file"
     fi
 }
 
 preloader() {
-    local preloaders=("$IMGS_DIR"/preloader*)
+    local preloaders=(preloader*)
     
     if [ ${#preloaders[@]} -gt 1 ]; then
-        echo -e "${y1} There are duplicate preloaders:${r5}"
+        echo -e "${y1}There are duplicate preloaders:${r5}"
         for i in "${!preloaders[@]}"; do
-            echo "$((i+1)). $(basename "${preloaders[$i]}")"
+            echo "$((i+1)). ${preloaders[$i]}"
         done
         
         while true; do
-            echo -ne "${y1} Select preloader (1-${#preloaders[@]}): ${r5}"
+            echo -ne "${y1}Select preloader (1-${#preloaders[@]}): ${r5}"
             read -r choice
             if [[ $choice =~ ^[1-${#preloaders[@]}]$ ]]; then
                 local selected="${preloaders[$((choice-1))]}"
-                log "${r3} Flashing preloader: $(basename "$selected")${r5}"
-                confirm " Flash preloader (a dangerous operation)" && \
+                log "${r3}Flashing preloader: $selected${r5}"
+                confirm " Flash preloader (dangerous operation)" && \
                 fastboot flash preloader "$selected"
                 return
             fi
-            echo -e "${r3} Invalid option!${r5}"
+            echo -e "${r3}Invalid option!${r5}"
         done
     elif [ ${#preloaders[@]} -eq 1 ]; then
-        confirm " Flash preloader $(basename "${preloaders[0]}") (a dangerous operation)" && \
+        confirm " Flash preloader ${preloaders[0]} (dangerous operation)" && \
         fastboot flash preloader "${preloaders[0]}"
     fi
 }
 
-log "${g3} Starting flash process:${r5}"
+log "${g3}Starting flash process${r5}"
 
 fastboot devices | grep -q "fastboot" || {
-    log "${r3} No device in fastboot mode!${r5}"
+    log "${r3}No device in fastboot mode!${r5}"
     exit 1
 }
 
-for vbmeta in "$IMGS_DIR"/vbmeta*.img; do
+check_images
+
+if [ "$1" == "all" ]; then
+    if confirm " ${r3}WARNING: This will ERASE ALL USER DATA!${r5} Continue?"; then
+        erase_partitions
+    else
+        log "${r3}Data wipe cancelled!${r5}"
+    fi
+elif [ "$1" == "keep_data" ]; then
+    log "${g3}Keeping user data (no wipe will be performed)${r5}"
+else
+    log "${r3}Unknown command!${r5}"
+    exit 1
+fi
+
+for vbmeta in vbmeta*.img; do
     [ -f "$vbmeta" ] || continue
     dv_vbmeta "$vbmeta" || {
-        log "${r3} Failed to flash $(basename "$vbmeta")!${r5}"
+        log "${r3}Failed to flash $vbmeta!${r5}"
     }
 done
 
 preloader
 
-for img in "$IMGS_DIR"/*.{img,bin}; do
+for img in *.img *.bin; do
     [ -f "$img" ] || continue
-    case $(basename "$img") in
+    case "$img" in
         vbmeta*|preloader*) continue ;;
         *)
             partition=$(basename "$img" .img)
             partition=$(basename "$partition" .bin)
-            log "${b1}  Flashing $partition...${r5}"
+            log "${b1}Flashing $partition...${r5}"
             fastboot flash "$partition" "$img" || {
-                log "${r3} Failed to flash $partition!${r5}"
+                log "${r3}Failed to flash $partition!${r5}"
             }
             ;;
     esac
 done
 
-log "${g3} SUCCESS:${r5} Flashing completed!"
-log " Reboot to: recovery"
+log "${g3}SUCCESS: Flashing completed!${r5}"
+log "Rebooting to recovery..."
 fastboot reboot recovery
